name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

permissions:
    contents: read
    pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ${{matrix.os}}
        if: always()
        strategy:
            matrix:
                include:
                    - {
                          os: windows-latest,
                          node: 14.19.3,
                          allowed-to-fail: false,
                      }
                    - {
                          os: windows-latest,
                          node: 16.15.1,
                          allowed-to-fail: true,
                      }
        continue-on-error: ${{matrix.allowed-to-fail}}

        steps:
            - uses: actions/checkout@v2

            - name: Setup node ${{matrix.node}}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{matrix.node}}

            - name: npm install
              run: |
                  npm install

            - name: Run build
              run: |
                  npm run build

            - name: Unit tests
              run: |
                  npm run coverage

            - name: Upload to codecov
              uses: codecov/codecov-action@v1
